server:
  port: 8080
  servlet:
    context-path:
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      #      ddl-auto: create
      #      ddl-auto: update
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/library_project
    username: root
    password: 123456789



  security:
    jwt:
      app:
        jwtSecret: 3778214125442A472D4B6150645367566B58703273357638792F423F4528482B
        #        jwtExpirationInMs: 300000
        #        jwtRefreshExpirationMs: 86400000
        jwtExpirationInMs: 30000000
        jwtRefreshExpirationMs: 86400000000

  cloudinary:
    cloud_name: dicwtezno
    api_key: 873674499332379
    api_secret: YSQmt8vfRpxB3ESGho9sYMe2H3Y

logging:
  level:
    org:
      hibernate:
        type:
          debug
  file:
    name: log/dev.log
